//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
		//Difference between lock and mutex in C#/.Net:
		//	Lock - per AppDomain (which is within a single process)
		//	Mutex - cross process locking / synchronization
		//Good AppDomain defintion: http://stackoverflow.com/questions/574708/what-is-appdomain
		//	An AppDomain provides a layer of isolation within a process. Everything you usually think of as "per program" (static variables etc) is actually per-AppDomain.
		public class FileIO
		{
				System.Object mutex = new System.Object ();
				public FileIO ()
				{
				}

				public string ReadFromFile (string fileName)
				{
						string text = string.Empty;
						try {
								using (System.IO.StreamReader file = new System.IO.StreamReader(fileName, true)) { 
										text = file.ReadToEnd ();
								}																
						} catch (Exception ex) {
								UnityEngine.Debug.LogError ("Error reading from file: " + ex.Message);
						}		
						return text;
				}

				public void WriteToFile (string fileName, string text)
				{						
						try {
								lock (mutex) {										
										System.IO.File.WriteAllText (fileName, text);						
								} //unlocks mutex								
						} catch (Exception ex) {
								UnityEngine.Debug.LogError ("Error writing to file: " + ex.Message);
						}
				}
		}
}

