//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
		public class Block
		{
				public float x;
				public float y;
				public float width;
				public float height;
				public UnityEngine.GameObject gameObject;

				public Block ()
				{
					
				}
				public Block (UnityEngine.GameObject gameObj)
				{
						gameObject = gameObj;
						x = gameObj.transform.position.x; 
						y = gameObj.transform.position.y;
						width = gameObj.renderer.bounds.size.x; 
						height = gameObj.renderer.bounds.size.y;

				}
				public void Tick () //eventually override this in the child class, once I start creating different types of blocks\
				{
						//I need to move down this object, assuming it is the current obj
						//rigidbody2D.transform.position.y -= .1;
					
				}				
		}
}

