//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
		public class Block
		{
				public Block ()
				{
					
				}
				public void Tick () //eventually override this in the child class, once I start creating different types of blocks\
				{
						//I need to move down this object, assuming it is the current obj
						//rigidbody2D.transform.position.y -= .1;
					
				}
		}
}

