//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
namespace AssemblyCSharp
{
		public class PlayerControl : MonoBehaviour
		{		
				private List<IInputObserver> registeredObservers = new List<IInputObserver> ();

				void Update ()
				{						
						if (Input.GetKeyDown (KeyCode.LeftArrow)) {
								NotifyObservers (KeyCode.LeftArrow);
						} else if (Input.GetKeyDown (KeyCode.RightArrow)) { 
								NotifyObservers (KeyCode.RightArrow);								
						} else if (Input.GetKeyDown (KeyCode.DownArrow)) { 
								NotifyObservers (KeyCode.DownArrow);								
						} else if (Input.GetKeyDown (KeyCode.UpArrow)) {							
								NotifyObservers (KeyCode.UpArrow);								
						} else if (Input.GetKeyDown (KeyCode.Escape))
								NotifyObservers (KeyCode.Escape);								
				}

				public void RegisterObserver (IInputObserver observer)
				{
						registeredObservers.Add (observer);
				}
				public void UnregisterObserver (IInputObserver observer)
				{
						registeredObservers.Remove (observer);
				}
				private void NotifyObservers (KeyCode pressedKey)
				{
						foreach (IInputObserver observer in registeredObservers) {
								observer.notify (pressedKey);
						}

				}		
		}
}


